print("Hola, ¿que tal?")
print("Vamos a realizar \"pruebas\" con el print")
print("Esta es una linea\nY esta es otra linea")
print("\t<--Lo anterior es una tabulación")
print("This isn\'t, permite escapar el apóstrofe")
print("Esto es -> \\ una barra")
print("Tu nombre completo es: " + input("Ingresa tu nombre: ") + " " + input("Dime tu apellido: "))